name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - ipykernel
  - jupyter_client
  - pip
  - pip:
    - dgl==1.1.0
    - huggingface-hub==0.15.1
    - lightgbm==3.3.5
    - matplotlib==3.7.1
    - numpy==1.24.2
    - pandas==2.0.0
    - pillow==9.5.0
    - requests==2.28.1
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - torch==2.0.0+cu117
    - torch-cluster==1.6.1+pt20cu117
    - torch-geometric==2.3.0
    - torch-scatter==2.1.1+pt20cu117
    - torch-sparse==0.6.17+pt20cu117
    - torch-spline-conv==1.2.2+pt20cu117
    - torchaudio==2.0.1+cu117
    - torchmetrics==0.11.4
    - torchvision==0.15.1+cu117
    - transformers==4.30.2
